name: Release and publish to NPM

on:
   push:
      branches:
         - main
         - beta

permissions:
   contents: write # to be able to publish a GitHub release
   issues: write # to be able to comment on released issues
   pull-requests: write # to be able to comment on released pull requests

jobs:
   release:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 20
              registry-url: 'https://registry.npmjs.org'

         - name: Install dependencies
           run: npm ci

         - name: Build
           run: npm run build
         
         - name: Copy Files
           run: cp -r dist/ package/ && cp package.json package/ && cp npm-shrinkwrap.json package/ && cp README.md package/ && cp LICENSE package/ && cp .npmrc package/ && cp -r templates/ package/ && chmod -R 777 package/ && chmod -R 777 dist/

         - name: Semantic Release
           run: npx semantic-release
           env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
