name: Release Beta

on:
  push:
    branches:
      - beta
      
permissions:
   contents: write
   pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build
        run: npm run build

      - name: Commit report
        continue-on-error: true
        run: |
          git config --global user.name 'Alexinhans'
          git config --global user.email 'Alexinhans@users.noreply.github.com'
          git commit -am "Automated push"
          git push

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

          