on:
   push:
     branches:
       - beta

permissions:
  contents: write
  pull-requests: write

name: release-please-beta

jobs:
  release-please-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          default-branch: beta
          manifest-file: release-please-config.json
          